{% set name = "readstat" %}
{% set version = "1.1.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/WizardMac/ReadStat/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 89af7c785a7ae3d9a7af6e64a69028829a429f66a14b1b913be22816dc07ddca

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libtool
    - autoconf
    - automake
    - make
    - cmake
    - m4
    - gettext
  host:
    - zlib
    - libiconv

test:
  commands:
    - readstat -h

about:
  home: https://github.com/WizardMac/ReadStat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command-line tool (+ C library) for converting SAS, Stata, and SPSS files

extra:
  recipe-maintainers:
    - izahn
