{% set name = "readstat" %}
{% set version = "1.1.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/WizardMac/ReadStat/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 814d4f4900d8b7a31989e4adcbaed79a480bdf09b3c72225cf9b9e5bec36b831

build:
  skip: true  # [win]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libtool
    - autoconf
    - automake
    - make
    - cmake
    - m4
    - gettext
  host:
    - zlib
    - libiconv

test:
  commands:
    - readstat -h

about:
  home: https://github.com/WizardMac/ReadStat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command-line tool (+ C library) for converting SAS, Stata, and SPSS files

extra:
  recipe-maintainers:
    - izahn
